<?php
/**
 * Copyright 2013 pixeltricks GmbH
 *
 * This file is part of SilverCart.
 *
 * SilverCart is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * SilverCart is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with SilverCart.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Extends the SilvercartOrderPosition object with voucher specific fields and methods.
 *
 * @package Silvercart
 * @package Vouchers
 * @author Sebastian Diel <sdiel@pixeltricks.de>
 * @since 02.12.2013
 * @copyright 2013 pixeltricks GmbH
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 */
class SilvercartVoucherShoppingCart extends DataObjectDecorator {
    
    /**
	 * Return TRUE if a method exists on this object
	 *
	 * This should be used rather than PHP's inbuild method_exists() as it takes into account methods added via
	 * extensions
	 *
	 * @param string $method Method to check
     * 
	 * @return bool
     * 
     * @author Sebastian Diel <sdiel@pixeltricks.de>
     * @since 02.12.2013
	 */
    public function hasMethod($method) {
        return method_exists($this, $method);
    }
    
    /**
     * Returns whether the current cart has a automatic generated voucher.
     * 
     * @return bool
     * 
     * @author Sebastian Diel <sdiel@pixeltricks.de>
     * @since 02.12.2013
     */
    public function hasAutoGeneratedVoucher() {
        return SilvercartAutoVoucherGenerator::has_voucher();
    }
    
    /**
     * Returns whether the current cart has a higher automatic generated voucher
     * than the currently active one.
     * 
     * @return bool
     * 
     * @author Sebastian Diel <sdiel@pixeltricks.de>
     * @since 02.12.2013
     */
    public function hasNextAutoGeneratedVoucher() {
        return SilvercartAutoVoucherGenerator::has_next_voucher();
    }
    
    /**
     * Returns the generator.
     * 
     * @return SilvercartAutoVoucherGenerator
     */
    public function getAutoVoucherGenerator() {
        return SilvercartAutoVoucherGenerator::get_valid_generator();
    }

    /**
     * Returns the custom shopping cart positions to render in template.
     * 
     * @param SilvercartShoppingCart $cart     Cart
     * @param Member                 $customer Customer
     * 
     * @return ArrayData
     * 
     * @author Sebastian Diel <sdiel@pixeltricks.de>
     * @since 02.12.2013
     */
    public function CustomShoppingCartPositions(SilvercartShoppingCart $cart, Member $customer) {
        return new ArrayData(array('CustomShoppingCartPosition' => $cart->renderWith('SilvercartAutoVoucherGeneratorPosition')));
    }
    
}